- name: deploy haproxy
  hosts: frontends
  become: true

  tasks:
  - name: Install httpie, haproxy
    yum:
      name: httpie, haproxy
      state: latest

  - name: enable haproxy
    service:
      name: haproxy
      state: started

  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:
  - name: restart haproxy
    service: name=haproxy state=restarted
